collector: use the app's software name and software version
Have verified that it would fail when setting the version as 2.0.0
in the regress test. This is the failure log:

```
$ go test -v ./collector/
=== RUN   TestSubmitIntegration
cannot open report: Opening report failed: request with body '{"probe_asn":"","probe_cc":"","software_name":"ooniprobe-android","software_version":"2.0.0","test_name":"tcp_connect","test_version":"0.0.1"}' has failed: POST https://c.collector.ooni.io:443/report failed: Request failed with status 400
cannot open report: Opening report failed: request with body '{"probe_asn":"","probe_cc":"","software_name":"ooniprobe-android","software_version":"2.0.0","test_name":"tcp_connect","test_version":"0.0.1"}' has failed: POST https://b.collector.ooni.io:443/report failed: Request failed with status 400
empty report ID, assuming failure

--- FAIL: TestSubmitIntegration (2.80s)
    collector_test.go:37: resubmission failed
FAIL
FAIL	github.com/measurement-kit/engine/collector	2.823s
```

Closes #10